config/routes.rb
Rails.application.routes.draw do

  devise_for :members
 resources :directories  

  root 'directories#index'

end

app/models/directory.rb
class Directory < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
	before_action :set_directory, only: [:show, :update, :destroy]
  def new
  	@directory = Directory.new
  end

  def edit

  end

  def show
  end

  def index
  	@directory = Directory.new
  	@directories = Directory.all		
  end

  def create
  	@directory  = Directory.new(directory_params)
  		respond_to do |format|
  			if @directory.save
  				format.html {redirect_to root_url, notice: "This member has been created successfully"}
  			else
  				format.html {render :new}
  			end
  		end
  end

  def update
 		respond_to do |format|
 			if @directory.update(directory_params)
  				format.html {redirect_to @directory, notice: "This member has been updated successfully"}
  			else
  				format.html {render :edit}
  			end
  		end
  	end
  

  def destroy
  	@directory.destroy
  		respond_to do |format| 
  			format.html {redirect_to directories_url, notice: "This member was deleted succesfully."} 
  		end
  end

private

  def directory_params
	params.require(:directory).permit(:name, :address, :phone, :alt_phone, :email, :h2h_group)
	
  end

  def set_directory
  	@directory = Directory.find(params[:id])
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/views/directories/_form.html.erb
<%= simple_form_for @directory do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone %>
  <%= f.input :alt_phone %>
  <%= f.input :email %>
  <%= f.input :h2h_group %>
  

  <%= f.button :submit %>
<% end %>

app/views/directories/edit.html.erb
<h1>Directories#edit</h1>
<p>Find me in app/views/directories/edit.html.erb</p>

<div class="container">
<%= render 'form' %>

</div>

<div>
<%= link_to 'Back', @directory %>
<%= link_to 'Home', directories_path %>
</div>

app/views/directories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>UCOC Member Directory</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone No.</th>
      <th>Alt. Phone</th>
      <th>Email</th>
      <th>H2H Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directories.each do |directory| %>
      <tr>
        <td><%= directory.name %></td>
        <td><%= directory.address %></td>
        <td><%= directory.phone %></td>
        <td><%= directory.alt_phone %></td>
        <td><%= directory.email %></td>
        <td><%= directory.h2h_group %></td>
        <td><%= link_to 'Show', directory %></td>
        <td><%= link_to 'Edit', edit_directory_path(directory) %></td>
        <td><%= link_to 'Destroy', root_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Add New Member", new_directory_path %>

app/views/directories/new.html.erb
<h1>University Church of Christ Member Directory</h1>
<p>Please enter all of the information in the Member Directory</p>
<%= render 'form' %>

app/views/directories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @directory.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @directory.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @directory.phone %>
</p>

<p>
  <strong>Alternate Phone:</strong>
  <%= @directory.alt_phone %>
</p>

<p>
  <strong>Email Address:</strong>
  <%= @directory.email %>
</p>

<p>
  <strong>House-to-House Group:</strong>
  <%= @directory.h2h_group %>
</p>

<%= link_to 'Edit', edit_directory_path(@directory) %> |
<%= link_to 'Back', directories_path %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">University Church of Christ </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Member Directory<span class="sr-only">(current)</span></a></li>
        <li><a href="#">Announcements</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">House-to-House Groups<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Group 1</a></li>
            <li><a href="#">Group 2</a></li>
            <li><a href="#">Group 3</a></li>
            <li><a href="#">Group 4</a></li>
            <li><a href="#">Group 5</a></li>
            <li><a href="#">Group 6</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Bible Study Curriculum</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Additional Resources</a></li>
          </ul>
        </li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
         <li><a href="#">Link</a></li>
        <% if current_member %>
          <li><%= link_to 'Sign Out', destroy_member_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_member_registration_path %></li>
          <li><%= link_to "Login", new_member_session_path %></li>
        <% end %> 
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ucoc</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>

<div class="container">	
<%= yield %>
</div>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


</body>
</html>